#!/usr/bin/env bash

for i in $(seq 1 100); do
  if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
    echo -n "FizzBuzz "
  elif [ $((i % 3)) -eq 0 ]; then
    echo -n "Fizz "
  elif [ $((i % 5)) -eq 0 ]; then
    echo -n "Buzz "
  else
    echo -n "$i "
  fi
done
